module.exports = {
    ar: {google: true, description: 'Arabic'},
    bg: {google: true, description: 'Bulgarian'},
    bn: {google: true, description: 'Bengali'},
    ca: {google: true, description: 'Catalan'},
    cs: {google: true, description: 'Czech'},
    da: {google: true, description: 'Danish'},
    de: {google: true, description: 'German'},
    el: {google: true, description: 'Greek'},
    en: {google: true, description: 'English'},
    en_GB: {google: true, description: 'English (Great Britain)', to: 'en'},
    en_US: {google: true, description: 'English (USA)', to: 'en'},
    es: {google: true, description: 'Spanish'},
    es_419: {google: true, description: 'Spanish (Latin America and Caribbean)', to: 'es'},
    et: {google: true, description: 'Estonian'},
    fa: {google: true, description: 'Persian'},
    fi: {google: true, description: 'Finnish'},
    fil: {google: true, description: 'Filipino', to: 'tl'},
    fr: {google: true, description: 'French'},
    gu: {google: true, description: 'Gujarati'},
    he: {google: true, description: 'Hebrew', to: 'iw'},
    hi: {google: true, description: 'Hindi'},
    hr: {google: true, description: 'Croatian'},
    hu: {google: true, description: 'Hungarian'},
    id: {google: true, description: 'Indonesian'},
    it: {google: true, description: 'Italian'},
    ja: {google: true, description: 'Japanese'},
    kn: {google: true, description: 'Kannada'},
    ko: {google: true, description: 'Korean'},
    lt: {google: true, description: 'Lithuanian'},
    lv: {google: true, description: 'Latvian'},
    
    mr: {google: true, description: 'Marathi'},
    ms: {google: true, description: 'Malay'},
    nl: {google: true, description: 'Dutch'},
    no: {google: true, description: 'Norwegian'},
    pl: {google: true, description: 'Polish'},
    pt_BR: {google: true, description: 'Portuguese (Brazil)', to: 'pt'},
    pt_PT: {google: true, description: 'Portuguese (Portugal)', to: 'pt'},
    ro: {google: true, description: 'Romanian'},
    ru: {google: true, description: 'Russian'},
    sk: {google: true, description: 'Slovak'},
    sl: {google: true, description: 'Slovenian'},
    sr: {google: true, description: 'Serbian'},
    sv: {google: true, description: 'Swedish'},
    sw: {google: true, description: 'Swahili'},
    ta: {google: true, description: 'Tamil'},
    te: {google: true, description: 'Telugu'},
    th: {google: true, description: 'Thai'},
    tr: {google: true, description: 'Turkish'},
    uk: {google: true, description: 'Ukrainian'},
    vi: {google: true, description: 'Vietnamese'},
    zh_CN: {google: true, description: 'Chinese (China)', to: 'zh-CN'},
    zh_TW: {google: true, description: 'Chinese (Taiwan)', to: 'zh-CN'},

    am: {description: 'Amharic'},
    ml: {description: 'Malayalam'}, // did a file 
    af: {description: 'Afrikaans'},
    sq: {description: 'Albanian'},
    hy: {description: 'Armenian'},
    az: {description: 'Azerbaijani'},
    eu: {description: 'Basque'},
    be: {description: 'Belarusian'},
    bs: {description: 'Bosnian'},
    ca: {description: 'Catalan'},
    ceb: {description: 'Cebuano'},
    eo: {description: 'Esperanto'},
    gl: {description: 'Galician'},
    ka: {description: 'Georgian'},
    ht: {description: 'Haitian Creole'},
    ha: {description: 'Hausa'},
    hmn: {description: 'Hmong'},
    is: {description: 'Icelandic'},
    ig: {description: 'Igbo'},
    ga: {description: 'Irish'},
    jw: {description: 'Javanese'},
    km: {description: 'Khmer'},
    lo: {description: 'Lao'},
    mk: {description: 'Macedonian'},
    mt: {description: 'Maltese'},
    mi: {description: 'Maori'},
    mn: {description: 'Mongolian'},
    ne: {description: 'Nepali'},
    pa: {description: 'Punjabi'},
    so: {description: 'Somali'},
    ur: {description: 'Urdu'},
    cy: {description: 'Welsh'},
    yi: {description: 'Yiddish'},
    yo: {description: 'Yoruba'},
    zu: {description: 'Zulu '}
};