module.exports = {
    ar: {description: 'Arabic'},
    am: {description: 'Amharic'}, // no ggtl support - no file yet
    bg: {description: 'Bulgarian'},
    bn: {description: 'Bengali'},
    ca: {description: 'Catalan'},
    cs: {description: 'Czech'},
    da: {description: 'Danish'},
    de: {description: 'German'},
    el: {description: 'Greek'},
    en: {description: 'English'},
    en_GB: {description: 'English (Great Britain)', to: 'en'},
    en_US: {description: 'English (USA)', to: 'en'},
    es: {description: 'Spanish'},
    es_419: {description: 'Spanish (Latin America and Caribbean)', to: 'es'},
    et: {description: 'Estonian'},
    fa: {description: 'Persian'},
    fi: {description: 'Finnish'},
    fil: {description: 'Filipino', to: 'tl'},
    fr: {description: 'French'},
    gu: {description: 'Gujarati'},
    he: {description: 'Hebrew', to: 'iw'},
    hi: {description: 'Hindi'},
    hr: {description: 'Croatian'},
    hu: {description: 'Hungarian'},
    id: {description: 'Indonesian'},
    it: {description: 'Italian'},
    ja: {description: 'Japanese'},
    kn: {description: 'Kannada'},
    ko: {description: 'Korean'},
    lt: {description: 'Lithuanian'},
    lv: {description: 'Latvian'},
    ml: {description: 'Malayalam'}, // no ggtl support
    mr: {description: 'Marathi'},
    ms: {description: 'Malay'},
    nl: {description: 'Dutch'},
    no: {description: 'Norwegian'},
    pl: {description: 'Polish'},
    pt_BR: {description: 'Portuguese (Brazil)', to: 'pt'},
    pt_PT: {description: 'Portuguese (Portugal)', to: 'pt'},
    ro: {description: 'Romanian'},
    ru: {description: 'Russian'},
    sk: {description: 'Slovak'},
    sl: {description: 'Slovenian'},
    sr: {description: 'Serbian'},
    sv: {description: 'Swedish'},
    sw: {description: 'Swahili'},
    ta: {description: 'Tamil'},
    te: {description: 'Telugu'},
    th: {description: 'Thai'},
    tr: {description: 'Turkish'},
    uk: {description: 'Ukrainian'},
    vi: {description: 'Vietnamese'},
    zh_CN: {description: 'Chinese (China)', to: 'zh-CN'},
    zh_TW: {description: 'Chinese (Taiwan)', to: 'zh-CN'}
};