module.exports = [
    {locale: 'ar', description: 'Arabic'},
    {locale: 'am', description: 'Amharic'}, // no ggtl support - no file yet
    {locale: 'bg', description: 'Bulgarian'},
    {locale: 'bn', description: 'Bengali'},
    {locale: 'ca', description: 'Catalan'},
    {locale: 'cs', description: 'Czech'},
    {locale: 'da', description: 'Danish'},
    {locale: 'de', description: 'German'},
    {locale: 'el', description: 'Greek'},
    {locale: 'en', description: 'English'},
    {locale: 'en_GB', description: 'English (Great Britain)', to: 'en'},
    {locale: 'en_US', description: 'English (USA)', to: 'en'},
    {locale: 'es', description: 'Spanish'},
    {locale: 'es_419', description: 'Spanish (Latin America and Caribbean)', to: 'es'},
    {locale: 'et', description: 'Estonian'},
    {locale: 'fa', description: 'Persian'},
    {locale: 'fi', description: 'Finnish'},
    {locale: 'fil', description: 'Filipino', to: 'tl'},
    {locale: 'fr', description: 'French'},
    {locale: 'gu', description: 'Gujarati'},
    {locale: 'he', description: 'Hebrew', to: 'iw'},
    {locale: 'hi', description: 'Hindi'},
    {locale: 'hr', description: 'Croatian'},
    {locale: 'hu', description: 'Hungarian'},
    {locale: 'id', description: 'Indonesian'},
    {locale: 'it', description: 'Italian'},
    {locale: 'ja', description: 'Japanese'},
    {locale: 'kn', description: 'Kannada'},
    {locale: 'ko', description: 'Korean'},
    {locale: 'lt', description: 'Lithuanian'},
    {locale: 'lv', description: 'Latvian'},
    {locale: 'ml', description: 'Malayalam'}, // no ggtl support
    {locale: 'mr', description: 'Marathi'},
    {locale: 'ms', description: 'Malay'},
    {locale: 'nl', description: 'Dutch'},
    {locale: 'no', description: 'Norwegian'},
    {locale: 'pl', description: 'Polish'},
    {locale: 'pt_BR', description: 'Portuguese (Brazil)', to: 'pt'},
    {locale: 'pt_PT', description: 'Portuguese (Portugal)', to: 'pt'},
    {locale: 'ro', description: 'Romanian'},
    {locale: 'ru', description: 'Russian'},
    {locale: 'sk', description: 'Slovak'},
    {locale: 'sl', description: 'Slovenian'},
    {locale: 'sr', description: 'Serbian'},
    {locale: 'sv', description: 'Swedish'},
    {locale: 'sw', description: 'Swahili'},
    {locale: 'ta', description: 'Tamil'},
    {locale: 'te', description: 'Telugu'},
    {locale: 'th', description: 'Thai'},
    {locale: 'tr', description: 'Turkish'},
    {locale: 'uk', description: 'Ukrainian'},
    {locale: 'vi', description: 'Vietnamese'},
    {locale: 'zh_CN', description: 'Chinese (China)', to: 'zh-CN'},
    {locale: 'zh_TW', description: 'Chinese (Taiwan)', to: 'zh-CN'}
];